import streamlit as st
import pandas as pd
import os

# Page Setting
st.set_page_config(page_title="Art Sales Tracker", page_icon="📈")

st.title("📈 Art Sales & Profit Tracker")
st.write("Apne art pieces ki sales, cost, aur profit margin ka hisaab yahan rakho!")

csv_file = "art_sales_data.csv"

# Form jisme tere saare original fields hain
with st.form("sales_form", clear_on_submit=True):
    item_name = st.text_input("Art/Item ka Naam:")
        
            # Numbers wale dabe
                items_sold = st.number_input("Number of Items Sold:", min_value=1, step=1)
                    cost_price = st.number_input("Cost Price (Ek piece ka ₹):", min_value=0.0, step=10.0)
                        selling_price = st.number_input("Selling Price (Ek piece ka ₹):", min_value=0.0, step=10.0)
                            
                                submit = st.form_submit_button("Entry CSV mein Save Karo")

                                    if submit:
                                            if item_name != "":
                                                        # Tera original calculations wala hissa!
                                                                    total_cost = items_sold * cost_price
                                                                                total_revenue = items_sold * selling_price
                                                                                            profit = total_revenue - total_cost
                                                                                                        
                                                                                                                    # Profit margin percentage nikalna
                                                                                                                                if total_cost > 0:
                                                                                                                                                profit_margin = (profit / total_cost) * 100
                                                                                                                                                            else:
                                                                                                                                                                            profit_margin = 0.0

                                                                                                                                                                                        # Data ko table format mein pack karo
                                                                                                                                                                                                    new_data = pd.DataFrame({
                                                                                                                                                                                                                    "Item Name": [item_name],
                                                                                                                                                                                                                                    "Items Sold": [items_sold],
                                                                                                                                                                                                                                                    "Cost Price (₹)": [cost_price],
                                                                                                                                                                                                                                                                    "Selling Price (₹)": [selling_price],
                                                                                                                                                                                                                                                                                    "Total Cost (₹)": [total_cost],
                                                                                                                                                                                                                                                                                                    "Total Revenue (₹)": [total_revenue],
                                                                                                                                                                                                                                                                                                                    "Profit (₹)": [profit],
                                                                                                                                                                                                                                                                                                                                    "Profit Margin (%)": [round(profit_margin, 2)]
                                                                                                                                                                                                                                                                                                                                                })

                                                                                                                                                                                                                                                                                                                                                            if os.path.exists(csv_file):
                                                                                                                                                                                                                                                                                                                                                                            new_data.to_csv(csv_file, mode='a', header=False, index=False)
                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                        new_data.to_csv(csv_file, index=False)
                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                    st.success(f"Ekdum Sahi! '{item_name}' ki entry register ho gayi. Profit: ₹{profit}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                st.balloons()
                                                                                                                                                                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.error("Arre! Item ka naam daalna bhool gayi.")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.write("---")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.subheader("📊 Tumhara Sales & Profit Record:")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if os.path.exists(csv_file):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        df = pd.read_csv(csv_file)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.dataframe(df)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Tera total munafa (profit) dikhane ke liye
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        total_profit = df["Profit (₹)"].sum()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.info(f"💰 Ab tak ka Total Profit: **₹{total_profit}**")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.info("Abhi tak koi sale entry nahi hui hai.")